spring:
  application:
    name: master-studio-front-website
  # 环境配置
  profiles:
    active: dev
  # json字符串解析配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    static-path-pattern: /static/**
  # 静态资源配置
#  web:
#    resources:
#      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${upload.file.save-path}
  # 线程池配置
#  task:
#    execution:
#      pool:
#        core-size: 20
#        max-size: 50
#        queue-capacity: 200